theme: jekyll-theme-minimal
title: My personal Projects
description: The objective of this website is to give an idea of the work developed and knowledge acquired in my personal projects.
logo: ![42362269_2359223604304895_865702850951380992_n](https://user-images.githubusercontent.com/70322978/91449586-310c6380-e873-11ea-9348-68386c86c494.jpg)
